### ISSUE TITLE
GTK+ 3.4 support

### ISSUE THREAD

**Issue by spvkgn** [slgobinath/SafeEyes#10]
Is there a way to add support for GTK+ 3.4 ?
```
Traceback (most recent call last):
  File "/opt/safeeyes/safeeyes", line 152, in <module>
    main()
  File "/opt/safeeyes/safeeyes", line 143, in main
    break_screen = BreakScreen(on_skipped, break_screen_glade, style_sheet_path)
  File "/opt/safeeyes/BreakScreen.py", line 38, in __init__
    builder.add_from_file(glade_file)
  File "/usr/lib/python2.7/dist-packages/gi/types.py", line 43, in function
    return info.invoke(*args, **kwargs)
gi._glib.GError: /opt/safeeyes/glade/break_screen.glade: required gtk+ version 3.10, current version is 3.4

~ $ dpkg -s libgtk-3-0|grep '^Version'
Version: 3.4.2-0ubuntu0.9
```

**Comment by slgobinath** [comment]
Could you please modify the required GTK version in both `/opt/safeeyes/glade/settings_dialog.glade` and `/opt/safeeyes/glade/break_screen.glade`.

Change the version in this line:
```
<requires lib="gtk+" version="3.10"/>
```
Please let me know the result after the modification. May I know your system configuration so that I can test Safe Eyes on it.

**Comment by spvkgn** [comment]
Thanks, it works with this change on Ubuntu 12.04 LTS.
