### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'python-xlib' distribution was not found and is required by safeeyes

### ISSUE THREAD

**Issue by jingle0927** [slgobinath/SafeEyes#220]
safeeyes 
Traceback (most recent call last):
  File "/usr/bin/safeeyes", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3037, in <module>
    @_call_aside
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3021, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3050, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 969, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 855, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python-xlib' distribution was not found and is required by safeeyes

**Comment by jingle0927** [comment]
Distribution  deepin 15.5

**Comment by jingle0927** [comment]
I Installed  though ppa

how can I add chinese

https://hosted.weblate.org/projects/safe-eyes/translations/

**Comment by slgobinath** [comment]
Could you please check whether `python3-xlib` is installed, though it is already added as a dependency in the debian package?

Chinese translation is not included in the current version but will be available from next version onwards.

**Comment by jingle0927** [comment]
Thanks @slgobinath
