### ISSUE TITLE
Fedora 27: Module xmlrpc.server not found & user instalation should be preferred

### ISSUE THREAD

**Issue by adimit** [slgobinath/SafeEyes#247]
Hi, I followed the installation instructions for Fedora precisely, but starting the program after `pip install`ing it results in the following error message:

```
Traceback (most recent call last):
  File "/usr/bin/safeeyes", line 11, in <module>
    load_entry_point('safeeyes==2.0.5', 'console_scripts', 'safeeyes')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 572, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2749, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2402, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2408, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/safeeyes/__main__.py", line 34, in <module>
    from safeeyes.SafeEyes import SafeEyes
  File "/usr/lib/python2.7/site-packages/safeeyes/SafeEyes.py", line 34, in <module>
    from safeeyes.rpc import RPCServer
  File "/usr/lib/python2.7/site-packages/safeeyes/rpc.py", line 25, in <module>
    from xmlrpc.server import SimpleXMLRPCServer
ImportError: No module named xmlrpc.server
```

I used the method in the Readme, using `sudo pip install` to arrive at the above result.

However, it is not generally a good idea to [`sudo pip install`](https://stackoverflow.com/questions/21055859/what-are-the-risks-of-running-sudo-pip/21056000#21056000) But installation into a user-local directory fails, as the setup assumes `/usr/share/icons/hicolor…` is writable. Icons for user installations should be put in `~/.local/share/icons/hicolor…` instead.

**Comment by slgobinath** [comment]
> ImportError: No module named xmlrpc.server

SafeEyes does not support Python 2 but your log says it is installed in Python 2.7. Could you please install it for Python 3 and check whether it works?

>  it is not generally a good idea

I +1 your suggestion. I will update the script.

**Comment by adimit** [comment]
Thanks for the quick response!
Interesting, I have both python 2 and 3 installed, but the `pip` command on Fedora seems to prefer Python 2. To install using python 3, I had to use `pip3`. It works now!
