### ISSUE TITLE
from xmlrpc.server import SimpleXMLRPCServer

### ISSUE THREAD

**Issue by yurivict** [slgobinath/SafeEyes#266]
I have py27-xmlrpc-0.8.8.3_3 installed, which is the latest version based on https://sourceforge.net/projects/py-xmlrpc/files/source/ , but still getting this error:
```
Traceback (most recent call last):
  File "/usr/local/bin/safeeyes", line 11, in <module>
    load_entry_point('safeeyes==2.0.6', 'console_scripts', 'safeeyes')()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 476, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2700, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2318, in load
    return self.resolve()
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2324, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/site-packages/safeeyes/__main__.py", line 34, in <module>
    from safeeyes.SafeEyes import SafeEyes
  File "/usr/local/lib/python2.7/site-packages/safeeyes/SafeEyes.py", line 34, in <module>
    from safeeyes.rpc import RPCServer
  File "/usr/local/lib/python2.7/site-packages/safeeyes/rpc.py", line 25, in <module>
    from xmlrpc.server import SimpleXMLRPCServer
ImportError: cannot import name SimpleXMLRPCServer
```

**Comment by slgobinath** [comment]
Hi,
Safe Eyes requires Python 3.
Could you please uninstall the existing Safe Eyes and install it using `sudo pip3 install safeeyes`

**Comment by yurivict** [comment]
Ok, thanks!
