### ISSUE TITLE
App doesn't want to work anymore

### ISSUE THREAD

**Issue by Serezon** [slgobinath/SafeEyes#290]
Was using SafeEyes for a few months, then turned it off for a while. Next time i tried to launch it again - nothing happened.
Manjaro, XFCE.
`safeeyes --debug
2018-11-17 22:52:22,345 [INFO]:[MainThread] Starting Safe Eyes
Traceback (most recent call last):
  File "/usr/bin/safeeyes", line 11, in <module>
    load_entry_point('safeeyes==2.0.6', 'console_scripts', 'safeeyes')()
  File "/usr/lib/python3.7/site-packages/safeeyes/__main__.py", line 141, in main
    safeeyes = SafeEyes(system_locale, config)
  File "/usr/lib/python3.7/site-packages/safeeyes/SafeEyes.py", line 77, in __init__
    self.break_screen = BreakScreen(self.context, self.on_skipped, self.on_postponed, Utility.STYLE_SHEET_PATH)
  File "/usr/lib/python3.7/site-packages/safeeyes/BreakScreen.py", line 47, in __init__
    self.display = Display()
  File "/usr/lib/python3.7/site-packages/Xlib/display.py", line 89, in __init__
    self.display = _BaseDisplay(display)
  File "/usr/lib/python3.7/site-packages/Xlib/display.py", line 71, in __init__
    protocol_display.Display.__init__(self, *args, **keys)
  File "/usr/lib/python3.7/site-packages/Xlib/protocol/display.py", line 167, in __init__
    raise error.DisplayConnectionError(self.display_name, r.reason)
Xlib.error.DisplayConnectionError: Can't connect to display ":0.0": b'Invalid MIT-MAGIC-COOKIE-1 key'
`

**Comment by Serezon** [comment]
Reinstalled my OS, it helped. Good luck
