### ISSUE TITLE
safe eyes will automatically disable in ubuntu 18.04

### ISSUE THREAD

**Issue by rezakalbaali** [slgobinath/SafeEyes#335]
`safeeyes --debug`

> 2019-09-03 18:39:29,592 [INFO]:[MainThread] Starting Safe Eyes
2019-09-03 18:39:29,653 [INFO]:[MainThread] Initialize the break screen
2019-09-03 18:39:29,653 [INFO]:[MainThread] Load all the plugins
2019-09-03 18:39:29,654 [INFO]:[MainThread] Initialize the core
2019-09-03 18:39:29,655 [INFO]:[MainThread] Successfully loaded <module 'donotdisturb.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/donotdisturb/plugin.py'>
2019-09-03 18:39:29,658 [INFO]:[MainThread] Successfully loaded <module 'notification.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/notification/plugin.py'>
2019-09-03 18:39:29,660 [INFO]:[MainThread] Successfully loaded <module 'audiblealert.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/audiblealert/plugin.py'>
2019-09-03 18:39:29,661 [INFO]:[MainThread] Successfully loaded <module 'trayicon.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/trayicon/plugin.py'>
2019-09-03 18:39:29,662 [INFO]:[MainThread] Successfully loaded <module 'smartpause.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/smartpause/plugin.py'>
2019-09-03 18:39:29,663 [INFO]:[MainThread] Successfully loaded <module 'screensaver.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/screensaver/plugin.py'>
2019-09-03 18:39:29,664 [INFO]:[MainThread] Successfully loaded <module 'healthstats.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/healthstats/plugin.py'>
2019-09-03 18:39:29,666 [INFO]:[MainThread] Successfully loaded <module 'mediacontrol.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/mediacontrol/plugin.py'>
2019-09-03 18:39:29,667 [DEBUG]:[MainThread] Initialize Skip Fullscreen plugin
2019-09-03 18:39:29,667 [DEBUG]:[MainThread] Initialize Notification plugin
2019-09-03 18:39:29,667 [DEBUG]:[MainThread] Initialize Audible Alert plugin
2019-09-03 18:39:29,667 [DEBUG]:[MainThread] Initialize Tray Icon plugin
2019-09-03 18:39:29,673 [DEBUG]:[MainThread] Initialize Smart Pause plugin
2019-09-03 18:39:29,674 [DEBUG]:[MainThread] Initialize Screensaver plugin
2019-09-03 18:39:29,674 [DEBUG]:[MainThread] Initialize Health Stats plugin
2019-09-03 18:39:29,677 [INFO]:[MainThread] Setting up an RPC server on port 7200
2019-09-03 18:39:29,678 [INFO]:[MainThread] Start the RPC server
2019-09-03 18:39:29,678 [DEBUG]:[MainThread] Start Smart Pause plugin
2019-09-03 18:39:29,678 [INFO]:[MainThread] Start Safe Eyes core
2019-09-03 18:39:29,679 [INFO]:[WorkThread] Waiting for 15 minutes until next break
2019-09-03 18:39:29,682 [INFO]:[MainThread] Update next break information
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/safeeyes/Utility.py", line 93, in <lambda>
    GLib.idle_add(lambda: target_function(args))
  File "/usr/lib/python3/dist-packages/safeeyes/SafeEyesCore.py", line 217, in __fire_on_update_next_break
    self.on_update_next_break.fire(self.break_queue.get_break(), next_break_time)
  File "/usr/lib/python3/dist-packages/safeeyes/model.py", line 227, in fire
    if not handler(*args, **keywargs):
  File "/usr/lib/python3/dist-packages/safeeyes/SafeEyes.py", line 274, in update_next_break
    self.plugins_manager.update_next_break(break_obj, break_time)
  File "/usr/lib/python3/dist-packages/safeeyes/PluginManager.py", line 163, in update_next_break
    plugin['module'].update_next_break(break_obj, break_time)
  File "/usr/lib/python3/dist-packages/safeeyes/plugins/trayicon/plugin.py", line 411, in update_next_break
    tray_icon.next_break_time(next_break_time)
  File "/usr/lib/python3/dist-packages/safeeyes/plugins/trayicon/plugin.py", line 260, in next_break_time
    self.__set_next_break_info()
  File "/usr/lib/python3/dist-packages/safeeyes/plugins/trayicon/plugin.py", line 266, in __set_next_break_info
    formatted_time = Utility.format_time(self.date_time)
  File "/usr/lib/python3/dist-packages/safeeyes/Utility.py", line 118, in format_time
    return babel.dates.format_time(time, format='short', locale=sys_locale)
  File "/usr/lib/python3/dist-packages/babel/dates.py", line 784, in format_time
    locale = Locale.parse(locale)
  File "/usr/lib/python3/dist-packages/babel/core.py", line 330, in parse
    raise UnknownLocaleError(input_id)
babel.core.UnknownLocaleError: unknown locale 'az_IR'
2019-09-03 18:39:35,704 [INFO]:[WorkThread] Pause Safe Eyes due to system idle
2019-09-03 18:39:35,704 [INFO]:[MainThread] Disable Safe Eyes
2019-09-03 18:39:35,707 [INFO]:[MainThread] Stop Safe Eye core
2019-09-03 18:39:35,707 [INFO]:[WorkThread] Pre-break waiting is over
2019-09-03 18:39:37,714 [INFO]:[WorkThread] Resume Safe Eyes due to user activity
Exception in thread WorkThread:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3/dist-packages/safeeyes/plugins/smartpause/plugin.py", line 135, in __start_idle_monitor
    next_break = next_break_time + idle_period
TypeError: unsupported operand type(s) for +: 'NoneType' and 'datetime.timedelta'

**Comment by zahramajd** [comment]
The same problem happens in ubuntu 20.04.

**Comment by vipulgupta2048** [comment]
Safe eyes not starting automatically on startup in xubuntu 18.04

**Comment by smith558** [comment]
> Safe eyes not starting automatically on startup in xubuntu 18.04

Same issue occuring on Ubuntu 20.04 LTS -> issue #367

**Comment by slgobinath** [comment]
@smith558 you get the same error?
```
TypeError: unsupported operand type(s) for +: 'NoneType' and 'datetime.timedelta'
```

**Comment by smith558** [comment]
> @smith558 you get the same error?
> 
> ```
> TypeError: unsupported operand type(s) for +: 'NoneType' and 'datetime.timedelta'
> ```
> 
> or
> 
> ```
> babel.core.UnknownLocaleError: unknown locale 'az_IR'
> ```
> 
> If so, would you mind testing the fix I have just committed in [0953abe](https://github.com/slgobinath/SafeEyes/commit/0953abe85575f2b2b8ef81c7af5600f84443e5e6) and [0953abe](https://github.com/slgobinath/SafeEyes/commit/0953abe85575f2b2b8ef81c7af5600f84443e5e6)
> 
> @ all sorry for not fixing this issue for this long. The fix was quite simple but don't know how I missed this issue.

@slgobinath I was just replying to @vipulgupta2048 . My issues is not related to #335 overall

**Comment by slgobinath** [comment]
Got it thanks

**Comment by vipulgupta2048** [comment]
Yes, I think mine got fixed after a simple reinstall or maybe it was updated.

**Comment by AdamPS** [comment]
Seems like it is fixed then
