### ISSUE TITLE
python-xlib missing in AUR dependencies

### ISSUE THREAD

**Issue by TAndronicus** [slgobinath/SafeEyes#350]
I'm using anaconda3-2019.07 globally with pyenv and I'm getting the following error when starting safeeyes:

Traceback (most recent call last):
  File "/home/jb/.pyenv/versions/anaconda3-2019.07/bin/safeeyes", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/jb/.pyenv/versions/anaconda3-2019.07/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3241, in <module>
    @_call_aside
  File "/home/jb/.pyenv/versions/anaconda3-2019.07/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3225, in _call_aside
    f(*args, **kwargs)
  File "/home/jb/.pyenv/versions/anaconda3-2019.07/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3254, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/jb/.pyenv/versions/anaconda3-2019.07/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/jb/.pyenv/versions/anaconda3-2019.07/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/jb/.pyenv/versions/anaconda3-2019.07/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'python-xlib' distribution was not found and is required by safeeyes

**Comment by slgobinath** [comment]
Hi `python-xlib` is a dependency required for Safe Eyes.
What's the Linux distribution you are using?

**Comment by TAndronicus** [comment]
Hi, 5.3.8-3-MANJARO, I've installed safeeyes using `yaourt -S safeeyes`

**Comment by slgobinath** [comment]
Hi,
Can you install `python-xlib` manually and see if it fixes the problem `sudo pacman -S python-xlib `?

**Comment by TAndronicus** [comment]
I did it, didn't help. The stacktrace is still the same.

**Comment by slgobinath** [comment]
> I'm using anaconda3-2019.07 globally with pyenv

Looks like something wrong with this environment in reading system's python-xlib. Is there a way to test if you have access to xlib in python?

**Comment by TAndronicus** [comment]
I installed it with some other dependencies through `conda install PyGObject python-xlib gtk2`, but I got
Traceback (most recent call last):
  File "/home/jb/.pyenv/versions/anaconda3-2019.07/bin/safeeyes", line 11, in <module>
    load_entry_point('safeeyes==2.0.9', 'console_scripts', 'safeeyes')()
  File "/home/jb/.pyenv/versions/anaconda3-2019.07/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/jb/.pyenv/versions/anaconda3-2019.07/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/jb/.pyenv/versions/anaconda3-2019.07/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/jb/.pyenv/versions/anaconda3-2019.07/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/jb/.pyenv/versions/anaconda3-2019.07/lib/python3.7/site-packages/safeeyes/__main__.py", line 32, in <module>
    from safeeyes import Utility
  File "/home/jb/.pyenv/versions/anaconda3-2019.07/lib/python3.7/site-packages/safeeyes/Utility.py", line 37, in <module>
    gi.require_version('Gtk', '3.0')
  File "/home/jb/.pyenv/versions/anaconda3-2019.07/lib/python3.7/site-packages/gi/__init__.py", line 133, in require_version
    (namespace, version))
ValueError: Namespace Gtk not available for version 3.0

**Comment by archisman-panigrahi** [comment]
This has been fixed.
