### ISSUE TITLE
How to run on macos?

### ISSUE THREAD

**Issue by d1y** [slgobinath/SafeEyes#355]
```console
> pip3 install safeeyes
> safeeyes
Warning: Failed to set locale category LC_NUMERIC to en_CN.
Warning: Failed to set locale category LC_TIME to en_CN.
Warning: Failed to set locale category LC_COLLATE to en_CN.
Warning: Failed to set locale category LC_MONETARY to en_CN.
Warning: Failed to set locale category LC_MESSAGES to en_CN.
Traceback (most recent call last):
  File "/usr/local/bin/safeeyes", line 5, in <module>
    from safeeyes.__main__ import main
  File "/usr/local/lib/python3.7/site-packages/safeeyes/__main__.py", line 34, in <module>
    from safeeyes.SafeEyes import SafeEyes
  File "/usr/local/lib/python3.7/site-packages/safeeyes/SafeEyes.py", line 28, in <module>
    import dbus
ModuleNotFoundError: No module named 'dbus'

```

**Comment by slgobinath** [comment]
Hi,

Safe Eyes only works on Linux, Similar problem is already discussed in #291

**Comment by d1y** [comment]
> Hi,
> 
> Safe Eyes only works on Linux, Similar problem is already discussed in #291

Yes. Thank you
