### ISSUE TITLE
[BUG] TypeError when trying to display next break time on tray

### ISSUE THREAD

**Issue by gorandp** [slgobinath/SafeEyes#416]
## `safeeyes --debug`

```
2021-01-20 08:32:18,122 [INFO]:[MainThread] Starting Safe Eyes
2021-01-20 08:32:18,205 [INFO]:[MainThread] Initialize the break screen
2021-01-20 08:32:18,205 [INFO]:[MainThread] Load all the plugins
2021-01-20 08:32:18,205 [INFO]:[MainThread] Initialize the core
2021-01-20 08:32:18,206 [INFO]:[MainThread] Successfully loaded <module 'donotdisturb.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/donotdisturb/plugin.py'>
2021-01-20 08:32:18,207 [INFO]:[MainThread] Successfully loaded <module 'notification.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/notification/plugin.py'>
2021-01-20 08:32:18,208 [INFO]:[MainThread] Successfully loaded <module 'audiblealert.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/audiblealert/plugin.py'>
2021-01-20 08:32:18,212 [INFO]:[MainThread] Successfully loaded <module 'trayicon.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/trayicon/plugin.py'>
2021-01-20 08:32:18,213 [INFO]:[MainThread] Successfully loaded <module 'screensaver.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/screensaver/plugin.py'>
2021-01-20 08:32:18,213 [INFO]:[MainThread] Successfully loaded <module 'healthstats.plugin' from '/usr/lib/python3/dist-packages/safeeyes/plugins/healthstats/plugin.py'>
2021-01-20 08:32:18,214 [DEBUG]:[MainThread] Initialize Skip Fullscreen plugin
2021-01-20 08:32:18,214 [DEBUG]:[MainThread] Initialize Notification plugin
2021-01-20 08:32:18,214 [DEBUG]:[MainThread] Initialize Audible Alert plugin
2021-01-20 08:32:18,214 [DEBUG]:[MainThread] Initialize Tray Icon plugin
2021-01-20 08:32:18,218 [DEBUG]:[MainThread] Initialize Screensaver plugin
2021-01-20 08:32:18,219 [DEBUG]:[MainThread] Initialize Health Stats plugin
2021-01-20 08:32:18,219 [INFO]:[MainThread] Setting up an RPC server on port 7200
2021-01-20 08:32:18,219 [INFO]:[MainThread] Start the RPC server
2021-01-20 08:32:18,219 [INFO]:[MainThread] Start Safe Eyes core
2021-01-20 08:32:18,220 [INFO]:[Thread-2] Waiting for 15 minutes until next break
2021-01-20 08:32:18,223 [INFO]:[MainThread] Update next break information
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/safeeyes/Utility.py", line 92, in <lambda>
    GLib.idle_add(lambda: target_function(args))
  File "/usr/lib/python3/dist-packages/safeeyes/SafeEyesCore.py", line 231, in __fire_on_update_next_break
    self.on_update_next_break.fire(self.breaks[self.next_break_index], next_break_time)
  File "/usr/lib/python3/dist-packages/safeeyes/model.py", line 108, in fire
    if not handler(*args, **keywargs):
  File "/usr/lib/python3/dist-packages/safeeyes/SafeEyes.py", line 249, in update_next_break
    self.plugins_manager.update_next_break(break_obj, break_time)
  File "/usr/lib/python3/dist-packages/safeeyes/PluginManager.py", line 162, in update_next_break
    plugin['module'].update_next_break(break_obj, break_time)
  File "/usr/lib/python3/dist-packages/safeeyes/plugins/trayicon/plugin.py", line 381, in update_next_break
    tray_icon.next_break_time(next_break_time)
  File "/usr/lib/python3/dist-packages/safeeyes/plugins/trayicon/plugin.py", line 247, in next_break_time
    self.__set_next_break_info()
  File "/usr/lib/python3/dist-packages/safeeyes/plugins/trayicon/plugin.py", line 254, in __set_next_break_info
    message = _('Next break at %s') % (formatted_time)
TypeError: not all arguments converted during string formatting
```

---

## Details

- Ubuntu 20.04.1 LTS (64 bits)
- Gnome 3.38.8
- safeeyes 2.0.6

## `apt show safeeyes`

```
Package: safeeyes
Version: 2.0.6-1
Priority: optional
Section: universe/utils
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Federico Ceratto <federico@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 1.134 kB
Depends: python3-babel, python3-gi, python3-psutil, python3-xlib, python3:any (>= 3.5~), python3-dbus, gir1.2-gtk-3.0
Recommends: gir1.2-appindicator3-0.1
Homepage: https://github.com/slgobinath/SafeEyes
Download-Size: 229 kB
```

**Comment by gorandp** [comment]
It works fine, it just doesn't show the next break time. And the error occurs after each break.

**Comment by slgobinath** [comment]
Hi, It looks like a problem with the translation.
Can you share the output of the `locale` command?

**Comment by gorandp** [comment]
Hi, sure :)
```
$ locale
LANG=es_AR.UTF-8
LANGUAGE=es_AR:es
LC_CTYPE="es_AR.UTF-8"
LC_NUMERIC="es_AR.UTF-8"
LC_TIME="es_AR.UTF-8"
LC_COLLATE="es_AR.UTF-8"
LC_MONETARY="es_AR.UTF-8"
LC_MESSAGES="es_AR.UTF-8"
LC_PAPER="es_AR.UTF-8"
LC_NAME="es_AR.UTF-8"
LC_ADDRESS="es_AR.UTF-8"
LC_TELEPHONE="es_AR.UTF-8"
LC_MEASUREMENT="es_AR.UTF-8"
LC_IDENTIFICATION="es_AR.UTF-8"
LC_ALL=
```

**Comment by slgobinath** [comment]
There is a bug in the 2.0.6 Spanish translation. Can you upgrade to the latest version or install it from the source?

PS: The latest version has another known bug related to Smart Pause. I recommend installing from the source for the moment.

**Comment by gorandp** [comment]
Thank you, I've installed using the `Installation guide` for Ubuntu in the `README.md` file and it works fine (the version installed now is `safeeyes 2.1.1`). I tried to update using the original Ubuntu repository but it didn't update. That's why I used your guide.

I won't use the Smart Pause, so I think it won't be an issue.

Thanks for your help!

**Comment by slgobinath** [comment]
Yeah the Ubuntu repo does not contain the latest version. I recommend installing my repo since I keep it up to date.
I'm closing this issue then.
