### ISSUE TITLE
SafeEyes startup fails on Void Linux

### ISSUE THREAD

**Issue by bnhrkn** [slgobinath/SafeEyes#463]
**Describe the bug**
SafeEyes startup fails with `socket.gaierror: [Errno -2] Name or service not known`

**To Reproduce**
1. Install safeeyes with `xbps-install -Su safeeyes` (install safeeyes and update system's packages)
2. Reboot
3. Run `safeeyes` in the terminal

**Expected behavior**
SafeEyes starts up successfully

**Desktop (please complete the following information):**
 - OS: Void Linux x86_64 glibc
 - Desktop Env: i3-gaps
 - Version: 2.1.3

**Debug Log**
```
2021-09-19 12:07:37,714 [DEBUG]:[MainThread] Initialize the platform
2021-09-19 12:07:37,725 [INFO]:[MainThread] Starting Safe Eyes
2021-09-19 12:07:37,726 [WARNING]:[MainThread] Unable to determine if wayland is running. Assuming no.
2021-09-19 12:07:37,747 [INFO]:[MainThread] Initialize the break screen
2021-09-19 12:07:37,747 [INFO]:[MainThread] Load all the plugins
2021-09-19 12:07:37,747 [INFO]:[MainThread] Initialize the core
2021-09-19 12:07:37,748 [INFO]:[MainThread] Successfully loaded <module 'donotdisturb.plugin' from '/usr/lib/python3.9/site-packages/safeeyes/plugins/donotdisturb/plugin.py'>
2021-09-19 12:07:37,749 [INFO]:[MainThread] Successfully loaded <module 'notification.plugin' from '/usr/lib/python3.9/site-packages/safeeyes/plugins/notification/plugin.py'>
2021-09-19 12:07:37,749 [INFO]:[MainThread] Successfully loaded <module 'audiblealert.plugin' from '/usr/lib/python3.9/site-packages/safeeyes/plugins/audiblealert/plugin.py'>
2021-09-19 12:07:37,750 [INFO]:[MainThread] Successfully loaded <module 'trayicon.plugin' from '/usr/lib/python3.9/site-packages/safeeyes/plugins/trayicon/plugin.py'>
2021-09-19 12:07:37,751 [INFO]:[MainThread] Successfully loaded <module 'screensaver.plugin' from '/usr/lib/python3.9/site-packages/safeeyes/plugins/screensaver/plugin.py'>
2021-09-19 12:07:37,752 [INFO]:[MainThread] Successfully loaded <module 'mediacontrol.plugin' from '/usr/lib/python3.9/site-packages/safeeyes/plugins/mediacontrol/plugin.py'>
2021-09-19 12:07:37,752 [DEBUG]:[MainThread] Initialize Skip Fullscreen plugin
2021-09-19 12:07:37,752 [DEBUG]:[MainThread] Initialize Notification plugin
2021-09-19 12:07:37,752 [DEBUG]:[MainThread] Initialize Audible Alert plugin
2021-09-19 12:07:37,752 [DEBUG]:[MainThread] Initialize Tray Icon plugin
2021-09-19 12:07:37,756 [DEBUG]:[MainThread] Initialize Screensaver plugin
2021-09-19 12:07:37,756 [INFO]:[MainThread] Setting up an RPC server on port 7200
Traceback (most recent call last):
  File "/bin/safeeyes", line 33, in <module>
    sys.exit(load_entry_point('safeeyes==2.1.3', 'console_scripts', 'safeeyes')())
  File "/usr/lib/python3.9/site-packages/safeeyes/__main__.py", line 148, in main
    safe_eyes.start()
  File "/usr/lib/python3.9/site-packages/safeeyes/safeeyes.py", line 108, in start
    self.__start_rpc_server()
  File "/usr/lib/python3.9/site-packages/safeeyes/safeeyes.py", line 322, in __start_rpc_server
    self.rpc_server = RPCServer(self.config.get('rpc_port'), self.context)
  File "/usr/lib/python3.9/site-packages/safeeyes/rpc.py", line 36, in __init__
    self.__server = SimpleXMLRPCServer(("localhost", port), logRequests=False, allow_none=True)
  File "/usr/lib/python3.9/xmlrpc/server.py", line 605, in __init__
    socketserver.TCPServer.__init__(self, addr, requestHandler, bind_and_activate)
  File "/usr/lib/python3.9/socketserver.py", line 452, in __init__
    self.server_bind()
  File "/usr/lib/python3.9/socketserver.py", line 466, in server_bind
    self.socket.bind(self.server_address)
socket.gaierror: [Errno -2] Name or service not known
```
[safeeyes.log](https://github.com/slgobinath/SafeEyes/files/7192453/safeeyes.log)

**Comment by slgobinath** [comment]
Hi Are there any other services listening on port number `7200`?

**Comment by bnhrkn** [comment]
No it does not appear so:
`sudo lsof -Pnl +M -i4`
```
COMMAND     PID     USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
rpcbind     782      997    6u  IPv4   21789      0t0  UDP *:111
rpcbind     782      997    7u  IPv4   21790      0t0  TCP *:111 (LISTEN)
rpc.statd   789        0    3u  IPv4   23206      0t0  UDP 127.0.0.1:965
rpc.statd   789        0    6u  IPv4   23210      0t0  UDP *:56477
rpc.statd   789        0    7u  IPv4   23212      0t0  TCP *:36929 (LISTEN)
dhcpcd      791        0   13u  IPv4   19297      0t0  UDP *:68
sshd        794        0    3u  IPv4   29482      0t0  TCP *:22 (LISTEN)
openntpd    816      991    6u  IPv4   51212      0t0  UDP 192.168.0.53:39652->X.X.X.X
openntpd    816      991    7u  IPv4 1071394      0t0  UDP 192.168.0.53:44665->X.X.X.X
openntpd    816      991    8u  IPv4  776373      0t0  UDP 192.168.0.53:52908->X.X.X.X
openntpd    816      991    9u  IPv4  146602      0t0  UDP 192.168.0.53:49211->X.X.X.X
dnsmasq     966       99    3u  IPv4   17255      0t0  UDP *:67
dnsmasq     966       99    5u  IPv4   17258      0t0  UDP 192.168.122.1:53
dnsmasq     966       99    6u  IPv4   17259      0t0  TCP 192.168.122.1:53 (LISTEN)
firefox    1341     1000   73u  IPv4 2944803      0t0  TCP 192.168.0.53:45038->X.X.X.X:443 (ESTABLISHED)
firefox    1341     1000   81u  IPv4 2943779      0t0  TCP 192.168.0.53:38818->X.X.X.X:443 (ESTABLISHED)
firefox    1341     1000   90u  IPv4 2941939      0t0  TCP 192.168.0.53:45402->X.X.X.X:443 (ESTABLISHED)
firefox    1341     1000  132u  IPv4 2956456      0t0  TCP 192.168.0.53:38820->X.X.X.X:443 (ESTABLISHED)
firefox    1341     1000  145u  IPv4 2950469      0t0  TCP 192.168.0.53:59126->X.X.X.X:443 (ESTABLISHED)
firefox    1341     1000  201u  IPv4   33885      0t0  TCP 192.168.0.53:42920->X.X.X.X:443 (ESTABLISHED)
Discord   16711     1000   30u  IPv4 2691621      0t0  TCP 192.168.0.53:36866->X.X.X.X:443 (ESTABLISHED)
Discord   16711     1000   31u  IPv4 2956120      0t0  TCP 192.168.0.53:60194->X.X.X.X:443 (ESTABLISHED)
Discord   16764     1000   36u  IPv4   68442      0t0  TCP 127.0.0.1:6463 (LISTEN)
```

**Comment by slgobinath** [comment]
I'm not sure why this happens. It may also happen if Safe Eyes cannot access `localhost`.
Can you try editing the `~/.config/safeeyes/safeeyes.json` file manually and change the https://github.com/slgobinath/SafeEyes/blob/master/safeeyes/config/safeeyes.json#L14 `use_rpc_server` value to `false` and open Safe Eyes?

**Comment by slgobinath** [comment]
Yeah that seems to be the issue. Thank you for updating.
I'm closing this issue as solved.
