### ISSUE TITLE
Full Screen Multi Monitor Bug 

### ISSUE THREAD

**Issue by ashvinnihalani** [slgobinath/SafeEyes#479]
**Describe the bug**
When you have an application in full-screen mode on one monitor, the break only appears on the second screen not the screen with the full-screen application. This is even with the DoNotDisturb Plugin disabled.

**To Reproduce**
1. Go to Youtube.com, and watch in a video in full screen
2. Wait for the timer to pass
3. The take a break screen only appears on the second screen

**Expected behavior**
The take a break screen should overlay the full-screen application as well.

**Desktop (please complete the following information):**
 - OS: Arch
 - Desktop Env KDE
 - Version [e.g. 2.1.3]

**Debug Log**
Error processing line 1 of /usr/lib/python3.10/site-packages/distutils-precedence.pth:

  Traceback (most recent call last):
    File "/usr/lib/python3.10/site.py", line 186, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
  AttributeError: module '_distutils_hack' has no attribute 'ensure_shim'

Remainder of file ignored
2022-05-14 21:22:35,480 [DEBUG]:[MainThread] Initialize the platform
2022-05-14 21:22:35,490 [INFO]:[MainThread] Starting Safe Eyes
2022-05-14 21:22:35,505 [INFO]:[MainThread] Initialize the break screen
2022-05-14 21:22:35,505 [INFO]:[MainThread] Load all the plugins
2022-05-14 21:22:35,506 [INFO]:[MainThread] Initialize the core
2022-05-14 21:22:35,506 [INFO]:[MainThread] Successfully loaded <module 'donotdisturb.plugin' from '/usr/lib/python3.10/site-packages/safeeyes/plugins/donotdisturb/plugin.py'>
2022-05-14 21:22:35,507 [INFO]:[MainThread] Successfully loaded <module 'notification.plugin' from '/usr/lib/python3.10/site-packages/safeeyes/plugins/notification/plugin.py'>
2022-05-14 21:22:35,507 [INFO]:[MainThread] Successfully loaded <module 'audiblealert.plugin' from '/usr/lib/python3.10/site-packages/safeeyes/plugins/audiblealert/plugin.py'>
2022-05-14 21:22:35,508 [INFO]:[MainThread] Successfully loaded <module 'trayicon.plugin' from '/usr/lib/python3.10/site-packages/safeeyes/plugins/trayicon/plugin.py'>
2022-05-14 21:22:35,509 [INFO]:[MainThread] Successfully loaded <module 'screensaver.plugin' from '/usr/lib/python3.10/site-packages/safeeyes/plugins/screensaver/plugin.py'>
2022-05-14 21:22:35,512 [INFO]:[MainThread] Successfully loaded <module 'healthstats.plugin' from '/usr/lib/python3.10/site-packages/safeeyes/plugins/healthstats/plugin.py'>
2022-05-14 21:22:35,512 [INFO]:[MainThread] Successfully loaded <module 'mediacontrol.plugin' from '/usr/lib/python3.10/site-packages/safeeyes/plugins/mediacontrol/plugin.py'>
2022-05-14 21:22:35,512 [DEBUG]:[MainThread] Initialize Skip Fullscreen plugin
2022-05-14 21:22:35,512 [DEBUG]:[MainThread] Initialize Notification plugin
2022-05-14 21:22:35,512 [DEBUG]:[MainThread] Initialize Audible Alert plugin
2022-05-14 21:22:35,512 [DEBUG]:[MainThread] Initialize Tray Icon plugin
2022-05-14 21:22:35,516 [DEBUG]:[MainThread] Initialize Screensaver plugin
2022-05-14 21:22:35,516 [DEBUG]:[MainThread] Initialize Health Stats plugin
2022-05-14 21:22:35,516 [DEBUG]:[MainThread] Health stats will be reset at 2022-05-15 00:00:00
2022-05-14 21:22:35,517 [DEBUG]:[MainThread] Resetting the health statistics
2022-05-14 21:22:35,517 [DEBUG]:[MainThread] Health stats will be reset at 2022-05-15 00:00:00
2022-05-14 21:22:35,517 [INFO]:[MainThread] Setting up an RPC server on port 7200
2022-05-14 21:22:35,518 [INFO]:[MainThread] Start the RPC server
2022-05-14 21:22:35,518 [INFO]:[MainThread] Start Safe Eyes core
2022-05-14 21:22:35,518 [INFO]:[WorkThread] Waiting for 20 minutes until next break
2022-05-14 21:22:35,520 [INFO]:[MainThread] Update next break information
2022-05-14 21:23:35,016 [INFO]:[MainThread] Show Settings dialog
2022-05-14 21:23:42,104 [INFO]:[MainThread] Saving settings to safeeyes.json
2022-05-14 21:23:42,105 [INFO]:[MainThread] Disable Safe Eyes
2022-05-14 21:23:42,106 [INFO]:[MainThread] Stop Safe Eyes core
2022-05-14 21:23:42,106 [INFO]:[WorkThread] Pre-break waiting is over
2022-05-14 21:23:42,108 [INFO]:[MainThread] Initialize SafeEyesCore with modified settings
2022-05-14 21:23:42,108 [INFO]:[MainThread] Initialize the core
2022-05-14 21:23:42,108 [INFO]:[MainThread] Initialize the break screen
2022-05-14 21:23:42,112 [DEBUG]:[MainThread] Initialize Skip Fullscreen plugin
2022-05-14 21:23:42,112 [DEBUG]:[MainThread] Initialize Notification plugin
2022-05-14 21:23:42,112 [DEBUG]:[MainThread] Initialize Audible Alert plugin
2022-05-14 21:23:42,112 [DEBUG]:[MainThread] Initialize Tray Icon plugin
2022-05-14 21:23:42,113 [DEBUG]:[MainThread] Initialize Screensaver plugin
2022-05-14 21:23:42,113 [DEBUG]:[MainThread] Initialize Health Stats plugin
2022-05-14 21:23:42,114 [DEBUG]:[MainThread] Health stats will be reset at 2022-05-15 00:00:00
2022-05-14 21:23:42,115 [INFO]:[MainThread] Enable Safe Eyes
2022-05-14 21:23:43,115 [INFO]:[Thread-3] Start Safe Eyes core
2022-05-14 21:23:43,116 [INFO]:[WorkThread] Waiting for 1 minutes until next break
2022-05-14 21:23:43,116 [INFO]:[MainThread] Update next break information
2022-05-14 21:24:43,117 [INFO]:[WorkThread] Pre-break waiting is over
2022-05-14 21:24:43,117 [INFO]:[MainThread] Show the notification
2022-05-14 21:24:43,134 [INFO]:[MainThread] Playing audible alert on_pre_break.wav
2022-05-14 21:24:44,136 [INFO]:[WorkThread] Wait for 10 seconds before the break
2022-05-14 21:24:54,137 [INFO]:[MainThread] Close pre-break notification
2022-05-14 21:24:54,147 [INFO]:[WorkThread] Lock the keyboard
2022-05-14 21:24:54,147 [INFO]:[MainThread] Show break screens in 2 display(s)
2022-05-14 21:24:54,169 [INFO]:[MainThread] Moved break screen to Display[1920, 0]
2022-05-14 21:24:54,174 [INFO]:[MainThread] Moved break screen to Display[0, 180]

**Comment by archisman-panigrahi** [comment]
Is the bug still present?
