### ISSUE TITLE
Error loading plugins in Python3.11

### ISSUE THREAD

**Issue by hsingko** [slgobinath/SafeEyes#491]
**Describe the bug**
Can't load those plugins on start.

**To Reproduce**
every time open safeeyes.

**Expected behavior**
- should show trayicon in system bar
- should get notification before breaks

**Desktop**
 - OS: Feodra 37
 - Desktop Env: wayland+gnome43
 - Version: 2.1.4
 - python version: 3.11

**Debug Log**
```log
2022-11-23 15:27:40,884 [DEBUG]:[MainThread] Initialize the platform
2022-11-23 15:27:40,910 [INFO]:[MainThread] Starting Safe Eyes
2022-11-23 15:27:40,999 [INFO]:[MainThread] Initialize the break screen
2022-11-23 15:27:40,999 [INFO]:[MainThread] Load all the plugins
2022-11-23 15:27:40,999 [INFO]:[MainThread] Initialize the core
2022-11-23 15:27:41,001 [ERROR]:[MainThread] Error in loading the plugin: notification
2022-11-23 15:27:41,002 [INFO]:[MainThread] Successfully loaded <module 'audiblealert.plugin' from '/home/hsingko/.local/lib/python3.11/site-packages/safeeyes/plugins/audiblealert/plugin.py'>
2022-11-23 15:27:41,002 [ERROR]:[MainThread] Error in loading the plugin: audiblealert
2022-11-23 15:27:41,004 [INFO]:[MainThread] Successfully loaded <module 'trayicon.plugin' from '/home/hsingko/.local/lib/python3.11/site-packages/safeeyes/plugins/trayicon/plugin.py'>
2022-11-23 15:27:41,004 [ERROR]:[MainThread] Error in loading the plugin: trayicon
2022-11-23 15:27:41,005 [INFO]:[MainThread] Successfully loaded <module 'smartpause.plugin' from '/home/hsingko/.local/lib/python3.11/site-packages/safeeyes/plugins/smartpause/plugin.py'>
2022-11-23 15:27:41,005 [ERROR]:[MainThread] Error in loading the plugin: smartpause
2022-11-23 15:27:41,006 [INFO]:[MainThread] Successfully loaded <module 'screensaver.plugin' from '/home/hsingko/.local/lib/python3.11/site-packages/safeeyes/plugins/screensaver/plugin.py'>
2022-11-23 15:27:41,006 [ERROR]:[MainThread] Error in loading the plugin: screensaver
2022-11-23 15:27:41,013 [INFO]:[MainThread] Successfully loaded <module 'healthstats.plugin' from '/home/hsingko/.local/lib/python3.11/site-packages/safeeyes/plugins/healthstats/plugin.py'>
2022-11-23 15:27:41,013 [ERROR]:[MainThread] Error in loading the plugin: healthstats
2022-11-23 15:27:41,014 [INFO]:[MainThread] Successfully loaded <module 'mediacontrol.plugin' from '/home/hsingko/.local/lib/python3.11/site-packages/safeeyes/plugins/mediacontrol/plugin.py'>
2022-11-23 15:27:41,014 [ERROR]:[MainThread] Error in loading the plugin: mediacontrol
2022-11-23 15:27:41,015 [INFO]:[MainThread] Setting up an RPC server on port 7200
2022-11-23 15:27:41,015 [INFO]:[MainThread] Start the RPC server
2022-11-23 15:27:41,015 [INFO]:[MainThread] Start Safe Eyes core
2022-11-23 15:27:41,016 [INFO]:[WorkThread] Waiting for 15 minutes until next break
2022-11-23 15:27:42,017 [INFO]:[MainThread] Show Settings dialog
```

**Screenshots**

![image](https://user-images.githubusercontent.com/74039541/203493221-0cd029fb-850a-4e48-a70b-7cd4ffccf22c.png)

**Comment by tibequadorian** [comment]
My investigation reveals the underlying error:
`module 'inspect' has no attribute 'getargspec'`

I'm sure this is because Python 3.11 dropped `inspect.getargspec` which was already deprecated.

**Comment by hsingko** [comment]
@tibequadorian 

this fix works fine, except `notification` plugin still doesn't work. I add a `traceback.print_exc()` before the `PluginManger.init log error` position, here is the trace:
```log
<@SafeEyes>-<⎇ master>-<±>-1-> python -m safeeyes
Traceback (most recent call last):
  File "/home/hsingko/Repos/SafeEyes/safeeyes/plugin_manager.py", line 86, in init
    self.__load_plugin(plugin)
  File "/home/hsingko/Repos/SafeEyes/safeeyes/plugin_manager.py", line 292, in __load_plugin
    module = importlib.import_module((plugin['id'] + '.plugin'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'notification.plugin'
ERROR:root:Error in loading the plugin: notification

```

**Comment by hsingko** [comment]
Python3.11 breaks so many packages, I rolled back to 3.10, `safeeyes` works now.

**Comment by tibequadorian** [comment]
@hsingko For me the notification plugin loads fine after applying the fix.

**Comment by LKHN** [comment]
@tibequadorian 

Everything works fine after applying the patch, Thank you very much!
