### ISSUE TITLE
ImportError: cannot import name 'LegacyVersion' from 'packaging.version'

### ISSUE THREAD

**Issue by Alirezaja1384** [slgobinath/SafeEyes#507]
**Describe the bug**
Safeeyes seems to have some dependency problems that broke the AUR package. If you try to install it using yay, It says:
```
==> Starting package()...
Traceback (most recent call last):
  File "/home/alireza/.cache/yay/safeeyes/src/SafeEyes-2.1.4/setup.py", line 3, in <module>
    import setuptools
  File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 247, in <module>
    monkey.patch_all()
  File "/usr/lib/python3.10/site-packages/setuptools/monkey.py", line 97, in patch_all
    patch_for_msvc_specialized_compiler()
  File "/usr/lib/python3.10/site-packages/setuptools/monkey.py", line 134, in patch_for_msvc_specialized_compiler
    msvc = import_module('setuptools.msvc')
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/setuptools/msvc.py", line 24, in <module>
    from packaging.version import LegacyVersion
ImportError: cannot import name 'LegacyVersion' from 'packaging.version' (/home/alireza/.local/lib/python3.10/site-packages/packaging/version.py)
==> ERROR: A failure occurred in package().
    Aborting...
 -> error making: safeeyes
```

**To Reproduce**
1. Run 'yay -S safeeyes'
2. Wait

**Expected behavior**
The package installs without any error.

**Desktop (please complete the following information):**
 - OS: EndeavourOS Linux x86_64
 - Desktop Env: Plasma 5.26.5
 - Version: 2.1.4-1

**Comment by Alirezaja1384** [comment]
The recent updates fixed this. I don't know if it was safeeyes' fault or python's or something else. Anyway, it seems to be fixed now. I'm going to close the issue. Thanks for the effort you put into this project.
